name: "Run TFLint on Main Branch"

on:
  push:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_LOG: INFO
  TF_STATE_S3_BUCKET: ${{ secrets.TF_STATE_S3_BUCKET}}
  TF_VERSION: 1.13.1

jobs:

  tflint:
    name: "Run TFLint on Terraform Code"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.52.0 

      - name: Run TFLint
        run: |
          tflint --init
          tflint --recursive --config "$(pwd)/.tflint.hcl"
        continue-on-error: true
