name: "Run TFLint and Ansible Molecule on Main Branch"

on:
  workflow_dispatch:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_LOG: INFO
  TF_STATE_S3_BUCKET: ${{ secrets.TF_STATE_S3_BUCKET}}
  TF_VERSION: 1.13.1

jobs:

  tflint:
    name: "Run TFLint on Terraform Code"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.52.0 

      - name: Run TFLint
        run: |
          tflint --init
          tflint --recursive --config "$(pwd)/.tflint.hcl"
        continue-on-error: true

  molecule:
    name: "Run Molecule on Ansible Code"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu22

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] molecule-plugins[docker] docker yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
